#!/bin/bash
python ./build_japan_training_data.py \
--waveform_root /opt/zb/data/japan \
--output_dir /opt/zb/data/japan \
--year 2024 \
--pick_mode travel_time \
--travel_time_model jma2001a \
--jma_search_margin_seconds 10 \
--run_diting \
--diting_p_th 0.1 \
--diting_s_th 0.1 \
--diting_d_th 0.1 \
--ditingbench_root /public/home/zhangbei/work_dir/zhangbei/xiaozhuowei/ditingbench \
--diting_weights /opt/zb/ckpt/1200m/dpk/720w_sft/model-4-latest.pth \
--diting_device cuda:0 \
--final_pick diting_vel \
--n_diagnostic_plots 48 \
--jma_search_margin_seconds 10.0 \
--jma_search_margin_per_km 0.03 \
--jma_search_margin_max_seconds 60.0 \
--fallback_search_half_window_seconds 60.0 \
--overwrite
